// 화면 문구는 전부 여기서 가져온다. 컴포넌트에 한국어 직접 삽입 금지.
// (단계 안내문 본문만 예외 — src/lib/steps.ts)

export const ko = {
  common: {
    appName: "온보딩 허브",
    loading: "불러오는 중…",
    save: "저장",
    saved: "저장되었습니다",
    cancel: "취소",
    delete: "삭제",
    confirm: "확인",
    edit: "수정",
    add: "추가",
    close: "닫기",
    back: "뒤로",
    copy: "복사",
    copied: "복사되었습니다",
    logout: "로그아웃",
    error: "문제가 생겼습니다. 잠시 후 다시 시도해 주세요.",
    empty: "아직 아무것도 없습니다.",
    notFound: "페이지를 찾을 수 없습니다.",
    openInNewTab: "새 탭에서 열기",
    required: "필수 입력입니다",
    invalidEmail: "이메일 형식이 아닙니다",
    invalidUrl: "주소(URL) 형식이 아닙니다",
    unauthorized: "접근 권한이 없습니다.",
  },

  login: {
    title: "로그인",
    description:
      "가입도 비밀번호도 없습니다. 이메일 주소를 입력하시면 로그인 링크를 보내드립니다.",
    emailLabel: "이메일 주소",
    emailPlaceholder: "you@example.com",
    submit: "로그인 링크 받기",
    submitting: "보내는 중…",
    sentTitle: "메일함을 확인해 주세요",
    sentDescription:
      "로그인 링크를 보냈습니다. 메일이 안 보이면 스팸함도 확인해 주세요. 링크는 24시간 동안 유효합니다.",
    resend: "다시 보내기",
    errorNoAccess:
      "이 이메일로 열린 프로젝트가 없습니다. 안내받은 이메일 주소가 맞는지 확인하시고, 다르면 담당자에게 알려 주세요.",
    errorAuth: "로그인 링크가 만료되었거나 잘못되었습니다. 다시 받아 주세요.",
  },

  status: {
    project: {
      onboarding: "온보딩",
      building: "개발 중",
      delivered: "전달 완료",
      closed: "종료",
    },
    step: {
      todo: "대기",
      doing: "진행 중",
      client_done: "완료 요청",
      verified: "확인 완료",
      blocked: "막힘",
      skipped: "건너뜀",
    },
    verify: {
      verified: "연결 확인됨",
      not_found: "아직 확인 안 됨",
      error: "확인 오류",
      never: "확인 전",
    },
    tier: {
      self: "셀프",
      assisted: "화면공유 지원",
    },
    ownerSide: {
      client: "의뢰인",
      agency: "제작자",
    },
  },

  portal: {
    homeTitle: "프로젝트 포털",
    progressLabel: "진행률",
    nextTaskTitle: "다음 할 일",
    nextTaskAllDone: "지금 하실 일이 없습니다. 나머지는 제가 진행하고 있어요.",
    nextTaskGo: "이어서 진행하기",
    linksTitle: "바로가기",
    linksEmpty: "등록된 링크가 아직 없습니다.",
    stepsTitle: "온보딩 단계",
    scopeTitle: "작업 범위",
    scopeEmpty: "작업 범위 문서가 아직 준비되지 않았습니다.",
    scopeAgreedAt: "확정일",
    commentsTitle: "질문·요청",
    closedNotice: "이 프로젝트는 종료되었습니다. 열람만 가능합니다.",
  },

  stepDetail: {
    yourTurn: "의뢰인이 진행하는 단계입니다",
    agencyTurn: "제작자가 진행하는 단계입니다. 기다려 주세요.",
    stageCreate: "1. 만들기",
    stageSlug: "2. 이름 알려주기",
    stageInvite: "3. 초대하기",
    stageVerify: "4. 연결 확인",
    createButton: (service: string) => `${service} 열기 (새 탭)`,
    createDone: "만들었습니다 — 다음 단계로",
    slugLabel: (noun: string) => `만든 ${noun}의 이름(주소)`,
    slugSave: "저장하고 다음으로",
    slugSaved: "저장되었습니다",
    slugNormalized: (slug: string) => `이렇게 저장됩니다: ${slug}`,
    slugEmptyError: "이름을 알아볼 수 없습니다. 주소를 통째로 붙여넣어 보세요.",
    inviteTitle: "제 계정을 초대해 주세요",
    inviteRole: (role: string) => `역할은 반드시 ${role} 로 지정해 주세요`,
    inviteCopyEmail: "초대할 이메일 복사",
    inviteOpenPage: "초대 화면 열기 (새 탭)",
    inviteHint:
      "이메일을 직접 입력하면 오타가 나기 쉽습니다. 꼭 복사 버튼을 사용해 주세요.",
    verifyButton: "연결 확인하기",
    verifyChecking: "확인하는 중…",
    verifiedTitle: "연결이 확인되었습니다. 감사합니다!",
    verifyNotFoundHint:
      "초대 직후에는 반영에 잠깐 시간이 걸릴 수 있습니다. 초대를 보내셨다면 잠시 후 다시 확인해 보세요.",
    verifyErrorHint:
      "확인 과정에 문제가 있습니다. 의뢰인 잘못이 아니니 그대로 두시면 제가 확인 후 처리하겠습니다.",
    stuckTitle: "자주 막히는 곳",
    doneButton: "완료했습니다",
    blockedButton: "막혔어요",
    helpButton: "화면공유로 도움받기",
    blockedPrompt: "어디서 막히셨는지 짧게 적어 주세요",
    blockedPlaceholder: "예: 조직을 만들었는데 초대 화면을 못 찾겠어요",
    blockedSubmit: "보내기",
    blockedSent: "전달되었습니다. 확인하는 대로 연락드릴게요.",
    helpSent:
      "요청이 전달되었습니다. 화면공유 일정을 잡아 연락드리겠습니다. 20분이면 충분합니다.",
    needHelpReason: "화면공유 도움 요청",
    doneSent: "확인 요청이 전달되었습니다. 제가 실제 연결 상태를 확인합니다.",
    blockedBanner: (reason: string) => `막힌 상태입니다 — ${reason}`,
    resume: "다시 진행하기",
  },

  comments: {
    title: "질문·요청",
    empty: "아직 남긴 글이 없습니다. 궁금한 것은 무엇이든 남겨 주세요.",
    kindQuestion: "질문",
    kindRequest: "요청",
    bodyPlaceholder: "카톡에 묻히지 않게, 여기에 남겨 주세요",
    submit: "남기기",
    submitting: "남기는 중…",
    deleted: "삭제된 글입니다",
    deleteConfirm: "이 글을 삭제할까요?",
    stepPrefix: "단계",
    markRead: "읽음 처리",
    unreadBadge: (count: number) => `안 읽음 ${count}`,
    mine: "나",
  },

  admin: {
    dashboardTitle: "프로젝트",
    newProject: "새 프로젝트",
    tableName: "이름",
    tableClient: "의뢰인",
    tableStatus: "상태",
    tableProgress: "진행률",
    tableOrgs: "조직 연결",
    tableUnread: "안 읽음",
    tableCreated: "생성일",
    emptyProjects: "프로젝트가 없습니다. 새 프로젝트를 만들어 시작하세요.",
    portalLink: "의뢰인 포털 열기",
    copyPortalLink: "포털 주소 복사",

    tabSteps: "단계",
    tabLinks: "링크",
    tabScope: "범위",
    tabSettings: "설정",
    tabClose: "종료",

    form: {
      code: "코드 (URL에 쓰이는 고유 slug)",
      codePlaceholder: "예: acme-shop",
      codeHelp: "포털 주소가 /p/코드 가 됩니다. 영문 소문자·숫자·하이픈만.",
      name: "프로젝트 이름",
      clientName: "의뢰인 이름",
      clientEmail: "의뢰인 이메일",
      clientEmailHelp:
        "이 이메일로 매직링크 로그인하면 포털 접근이 열립니다. 초대 메일을 따로 보내지 않습니다.",
      supportTier: "지원 등급",
      status: "프로젝트 상태",
      githubOrg: "GitHub 조직",
      vercelTeam: "Vercel 팀",
      supabaseOrg: "Supabase 조직",
      domain: "도메인",
      create: "프로젝트 만들기",
      creating: "만드는 중…",
      createHelp: "생성하면 온보딩 단계가 템플릿에서 복사되어 채워집니다.",
      guests: "포털 접근 이메일",
      guestsHelp: "의뢰인 쪽에서 포털에 들어올 수 있는 이메일 목록입니다.",
      addGuest: "이메일 추가",
      codeDuplicate: "이미 사용 중인 코드입니다.",
      invalidCode: "영문 소문자·숫자·하이픈만 쓸 수 있습니다.",
    },

    steps: {
      verifyNow: "지금 확인",
      markVerified: "확인 완료로",
      markSkipped: "건너뜀으로",
      reset: "대기로 되돌리기",
      lastVerify: "마지막 확인",
      blockedReason: "막힌 사유",
      clientDoneAt: "완료 요청 시각",
    },

    links: {
      label: "이름",
      url: "주소",
      pinned: "고정",
      pinnedHelp: "고정하면 포털 홈 최상단에 큰 버튼으로 보입니다.",
      addLink: "링크 추가",
      empty: "등록된 링크가 없습니다.",
      unpin: "고정 해제",
      pin: "고정",
    },

    scope: {
      title: "작업 범위 (Markdown)",
      help: "통화·미팅에서 합의한 범위를 정리해 적는다. 의뢰인은 읽기 전용.",
      agree: "이 내용으로 범위 확정",
      agreedAt: (date: string) => `${date} 확정됨`,
      notAgreed: "아직 확정 전",
      requestsSince: (count: number) => `확정 이후 들어온 요청 ${count}건`,
      requestsHelp: "확정 이후 쌓인 요청 수가 곧 범위 증가분이다.",
      preview: "미리보기",
    },

    offboard: {
      title: "종료 체크리스트",
      help: "위에서부터 순서대로만 진행한다. 특히 토큰 폐기가 멤버 탈퇴보다 먼저다.",
      completeButton: "프로젝트 종료 처리",
      completeConfirm:
        "체크리스트를 모두 마쳤습니까? 종료하면 상태가 closed로 바뀝니다.",
      closedAt: (date: string) => `${date} 종료됨`,
      notReady: "위 항목을 순서대로 모두 체크하면 종료할 수 있습니다.",
    },
  },

  cost: {
    title: "월 고정비 계산기",
    description:
      "서비스 운영에 매달 들어가는 고정비를 계산합니다. 의뢰인 안내용.",
    tableService: "서비스",
    tablePlan: "요금제",
    tablePrice: "비용",
    tableNote: "비고",
    perMonth: (usd: number) => `$${usd}/월`,
    perYearKrw: (krw: number) => `연 ${krw.toLocaleString("ko-KR")}원`,
    freeLabel: "무료",
    totalTitle: "합계",
    totalMonthly: (usd: number, krw: number) =>
      `월 $${usd} (약 ${krw.toLocaleString("ko-KR")}원)`,
    disclaimer:
      "환율과 요금제는 바뀔 수 있습니다. 정확한 금액은 각 서비스의 결제 화면 기준입니다.",
  },

  privacy: {
    title: "개인정보 처리방침",
  },
} as const;
